/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/r0MLepAvqUk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Judson } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'
import { useState } from "react"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"


const FavPoke = () => {
  const [name, setName] = useState('');
  const [favouritePokemon, setFavoritePokemon] = useState('');
  const [favouriteMove, setFavoriteMove] = useState('');
  const [reason, setReason] = useState('');
  const [message, setMessage] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    const response = await fetch(`http://localhost:3001/api/user`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ name, favouritePokemon, favouriteMove, reason })
    });

    const data = await response.json();
    if (response.ok) {
      setMessage(data.message);
      setName('');
      setFavoritePokemon('');
      setFavoriteMove('');
      setReason('');
    } else {
      setMessage('Failed to add user: ' + data.message);
    }
  };

  return (
    <div>
    <main
      className="flex min-h-[100dvh] items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-950">
      <div
        className="mx-auto w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
        <h1 className="mb-6 text-3xl font-bold">Tell us about your favorite Pokemon!</h1>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label htmlFor="name">Name</Label>
            <Input id="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Enter your name" required />
          </div>
          <div>
            <Label htmlFor="pokemon">Favorite Pokemon</Label>
            <Input id="pokemon" value={favouritePokemon} onChange={(e) => setFavoritePokemon(e.target.value)} required placeholder="Enter your favorite Pokemon" />
          </div>
          <div>
            <Label htmlFor="move">Favorite Move</Label>
            <Input id="move" value={favouriteMove} onChange={(e) => setFavoriteMove(e.target.value)} required placeholder="Enter your favorite move" />
          </div>
          <div>
            <Label htmlFor="reason">Why is this your favorite Pokemon?</Label>
            <Textarea
              className="min-h-[100px]"
              id="reason"
              value={reason} onChange={(e) => setReason(e.target.value)} required
              placeholder="Explain why this move is your favorite" />
          </div>
          <Button className="w-full" type="submit">
            Submit
          </Button>
        </form>
      </div>
    </main>
    </div>
  );
};

export default FavPoke;
